[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:1420"
additional_redirect_urls = [
  "http://localhost:1420",
  "http://localhost:5173",
  "http://tauri.localhost",
  "https://staging-app.glazebot.gg",
  "https://app.glazebot.gg",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
otp_length = 6
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_AUTH_CLIENT_ID)"
secret = "env(GOOGLE_AUTH_CLIENT_SECRET)"
